

import { ToolDef, ToolCategory } from './types';
import {
  Archive,
  ArrowRightLeft,
  Binary,
  Braces,
  BrainCircuit,
  Calculator,
  Calendar,
  Clock,
  Code,
  Code2,
  Cpu,
  Database,
  DollarSign,
  Eye,
  FileCode,
  FileJson,
  FileSearch,
  FileText,
  Globe,
  Hash,
  Image,
  Key,
  Link as LinkIcon,
  Lock,
  Minimize2,
  Monitor,
  Palette,
  QrCode,
  Regex,
  Ruler,
  Search,
  Shield,
  ShieldCheck,
  Shuffle,
  Share2,
  Table,
  Type,
  Wand2,
  Wifi,
  GitCompare,
  Fingerprint,
  CalendarClock,
  Split,
  FileDigit,
  FileCode2,
  Terminal,
  Layers,
  Box,
  FileSpreadsheet
} from 'lucide-react';

export const ALL_TOOLS: ToolDef[] = [
  // --- ESSENTIAL DEVELOPER TOOLS ---
  { id: 'json-formatter', name: 'JSON Formatter', description: 'Beautify, minify and validate JSON.', category: ToolCategory.JSON, path: '/json-formatter', icon: FileJson, popular: true, tags: ['json', 'format', 'beautify', 'minify', 'validate', 'pretty print'] },
  { id: 'base64-converter', name: 'Base64 Converter', description: 'Encode and decode Base64 strings.', category: ToolCategory.CONVERTER, path: '/base64-converter', icon: Binary, popular: true, tags: ['base64', 'encode', 'decode', 'converter', 'encoding'] },
  { id: 'jwt-decoder', name: 'JWT Decoder', description: 'Decode JSON Web Tokens.', category: ToolCategory.DEV, path: '/jwt-decoder', icon: ShieldCheck, popular: true, tags: ['jwt', 'token', 'decode', 'auth', 'authentication', 'security'] },
  { id: 'regex-tester', name: 'Regex Tester', description: 'Test regular expressions.', category: ToolCategory.DEV, path: '/regex-tester', icon: Regex, isNew: true, popular: true, tags: ['regex', 'regexp', 'regular expression', 'pattern', 'match', 'test'] },
  { id: 'diff', name: 'Text Diff', description: 'Compare two text files.', category: ToolCategory.STRING, path: '/diff-viewer', icon: GitCompare, popular: true, tags: ['diff', 'compare', 'difference', 'merge', 'text comparison'] },
  // Note: MD5/SHA are provided as utility tools, not for security purposes
  { id: 'hash-gen', name: 'Hash Generator', description: 'Generate MD5, SHA256 hashes.', category: ToolCategory.CRYPTO, path: '/hash-generator', icon: Hash, popular: true, tags: ['hash', 'md5', 'sha', 'sha256', 'checksum', 'crypto'] },
  { id: 'uuid-gen', name: 'UUID Generator', description: 'Generate Version 4 UUIDs.', category: ToolCategory.RANDOM, path: '/uuid-generator', icon: Fingerprint, popular: true, tags: ['uuid', 'guid', 'unique id', 'random', 'identifier'] },
  { id: 'code-formatter', name: 'Code Beautifier', description: 'Format HTML, CSS, and JS.', category: ToolCategory.FORMATTER, path: '/code-formatter', icon: Wand2, popular: true, tags: ['code', 'format', 'beautify', 'html', 'css', 'js', 'javascript', 'prettier'] },
  { id: 'url-encoder', name: 'URL Encoder', description: 'Encode/Decode URLs.', category: ToolCategory.ENCODE, path: '/url-encoder', icon: LinkIcon, popular: true, tags: ['url', 'encode', 'decode', 'uri', 'link', 'percent encoding'] },
  { id: 'date-converter', name: 'Date Converter', description: 'Epoch & ISO date conversion.', category: ToolCategory.DEV, path: '/date-converter', icon: CalendarClock, isNew: true, popular: true, tags: ['date', 'epoch', 'unix', 'timestamp', 'iso', 'time'] },
  { id: 'sql-format', name: 'SQL Formatter', description: 'Format and beautify SQL queries.', category: ToolCategory.SQL, path: '/sql-formatter', icon: Database, popular: true, tags: ['sql', 'format', 'query', 'database', 'beautify'] },
  { id: 'password-gen', name: 'Password Gen', description: 'Generate secure passwords.', category: ToolCategory.RANDOM, path: '/password-generator', icon: Lock, popular: true, tags: ['password', 'generate', 'random', 'secure', 'strong password'] },

  // --- BATCH 8 (Ultimate Collection) ---
  { id: 'rsa-gen', name: 'RSA Key Generator', description: 'Generate PEM Public/Private keys.', category: ToolCategory.CRYPTO, path: '/rsa-generator', icon: Key, isNew: true },
  { id: 'token-gen', name: 'Token Generator', description: 'Generate random API keys/secrets.', category: ToolCategory.RANDOM, path: '/token-generator', icon: Key, isNew: true },
  { id: 'http-status', name: 'HTTP Status Codes', description: 'Searchable status code reference.', category: ToolCategory.DEV, path: '/http-status-codes', icon: Globe, isNew: true },
  { id: 'meta-tag', name: 'Meta Tag Gen', description: 'SEO meta tags for websites.', category: ToolCategory.HTML_GEN, path: '/meta-tag-generator', icon: FileSearch, isNew: true },
  { id: 'palette-ext', name: 'Palette Extractor', description: 'Get colors from any image.', category: ToolCategory.COLOR, path: '/palette-extractor', icon: Palette, isNew: true },

  // --- BATCH 7 (Final Polish) ---
  { id: 'markdown-editor', name: 'Markdown Editor', description: 'Write MD with live preview.', category: ToolCategory.EDITOR, path: '/markdown-editor', icon: FileText, isNew: true },
  { id: 'bcrypt-gen', name: 'Bcrypt Generator', description: 'Hash and verify passwords.', category: ToolCategory.CRYPTO, path: '/bcrypt-generator', icon: Lock, isNew: true },
  { id: 'bitwise', name: 'Bitwise Calculator', description: 'AND, OR, XOR, logic ops.', category: ToolCategory.MATH, path: '/bitwise-calculator', icon: Cpu, isNew: true },
  { id: 'hmac-gen', name: 'HMAC Generator', description: 'Keyed-hash msg auth code.', category: ToolCategory.CRYPTO, path: '/hmac-generator', icon: Shield, isNew: true },
  { id: 'slug-gen', name: 'Slug Generator', description: 'URL-friendly text slug.', category: ToolCategory.STRING, path: '/slug-generator', icon: LinkIcon, isNew: true },

  // --- BATCH 6 ---
  { id: 'list-comp', name: 'List Comparator', description: 'Diff lists (Union, Intersection).', category: ToolCategory.STRING, path: '/list-comparator', icon: Split, isNew: true },
  { id: 'case-conv', name: 'Case Converter', description: 'Camel, Snake, Kebab case.', category: ToolCategory.STRING, path: '/case-converter', icon: Type, isNew: true },
  { id: 'ua-parser', name: 'User Agent Parser', description: 'Decode browser User Agent.', category: ToolCategory.DEV, path: '/ua-parser', icon: Monitor, isNew: true },

  // --- BATCH 4 & 5 ---
  { id: 'gzip', name: 'GZip Compressor', description: 'Compress text to GZip Base64.', category: ToolCategory.COMPRESSION, path: '/gzip-compressor', icon: Archive },
  { id: 'qrcode', name: 'QR Code Gen', description: 'Generate QR Codes.', category: ToolCategory.HTML_GEN, path: '/qrcode-generator', icon: QrCode },
  { id: 'chmod', name: 'Chmod Calculator', description: 'Linux permissions calculator.', category: ToolCategory.DEV, path: '/chmod-calculator', icon: Terminal },
  { id: 'cron', name: 'Cron Generator', description: 'Create cron schedule strings.', category: ToolCategory.DEV, path: '/cron-generator', icon: Clock },

  // --- PREVIOUSLY ADDED ---
  { id: 'xml-json', name: 'XML <> JSON', description: 'Convert XML to JSON and back.', category: ToolCategory.XML, path: '/xml-json-converter', icon: ArrowRightLeft },
  { id: 'dns-lookup', name: 'DNS Lookup', description: 'Find DNS records (A, MX, NS).', category: ToolCategory.NETWORK, path: '/dns-lookup', icon: Globe },
  { id: 'pojo', name: 'POJO Generator', description: 'Generate Java classes from JSON.', category: ToolCategory.POJO, path: '/pojo-generator', icon: FileCode2 },
  { id: 'utf8-conv', name: 'UTF8 Converter', description: 'Text to Hex/Binary bytes.', category: ToolCategory.UTF, path: '/utf8-converter', icon: Binary },
  { id: 'csv-xml', name: 'CSV to XML', description: 'Convert CSV to XML.', category: ToolCategory.CSV, path: '/csv-to-xml', icon: Table },
  { id: 'csv-json-t', name: 'CSV to JSON', description: 'Convert CSV to JSON format.', category: ToolCategory.CSV, path: '/csv-converter', icon: Table },
  { id: 'css-unit', name: 'CSS Unit Converter', description: 'Convert PX, REM, EM, %.', category: ToolCategory.CSS_UNIT, path: '/css-unit-converter', icon: Ruler },
  { id: 'twitter', name: 'Twitter Card Gen', description: 'Generate social meta tags.', category: ToolCategory.TWITTER, path: '/twitter-card-generator', icon: Share2 },
  { id: 'json-converter', name: 'JSON Converter', description: 'Convert JSON to XML/CSV.', category: ToolCategory.JSON, path: '/json-converter', icon: ArrowRightLeft },
  { id: 'gst-calc', name: 'GST Calculator', description: 'Calculate GST inclusive/exclusive.', category: ToolCategory.FINANCE, path: '/gst-calculator', icon: DollarSign },
  { id: 'html-strip', name: 'HTML Stripper', description: 'Remove HTML tags from text.', category: ToolCategory.HTML, path: '/html-stripper', icon: Code },
  { id: 'rand-gen', name: 'Random Generator', description: 'Generate random numbers/strings.', category: ToolCategory.RANDOM_GEN, path: '/random-generator', icon: Shuffle },
  { id: 'tsv-json', name: 'TSV to JSON', description: 'Convert TSV to JSON.', category: ToolCategory.TSV, path: '/tsv-converter', icon: Table },
  { id: 'sql-json', name: 'SQL to JSON', description: 'Convert SQL to JSON/CSV.', category: ToolCategory.SQL, path: '/sql-converter', icon: Database },

  // --- OTHERS ---
  { id: 'ai-assistant', name: 'AI Code Helper', description: 'Ask Gemini to write/debug code.', category: ToolCategory.AI, path: '/ai-assistant', icon: BrainCircuit },
  { id: 'my-ip', name: 'My IP Address', description: 'Show public IP & device info.', category: ToolCategory.NETWORK, path: '/my-ip', icon: Wifi },
  { id: 'xml-beautify', name: 'XML Formatter', description: 'Format and validate XML data.', category: ToolCategory.XML, path: '/xml-formatter', icon: FileCode },
  { id: 'word-count', name: 'Word Counter', description: 'Count words and lines.', category: ToolCategory.STRING, path: '/word-counter', icon: Type },
  { id: 'lorem', name: 'Lorem Ipsum', description: 'Generate filler text.', category: ToolCategory.STRING, path: '/lorem-ipsum', icon: FileText },
  { id: 'text-style', name: 'Text Styler', description: 'Fancy text generator.', category: ToolCategory.TEXT_STYLE, path: '/text-styler', icon: Type },
  { id: 'hex-rgb', name: 'HEX to RGB', description: 'Convert HEX to RGB.', category: ToolCategory.COLOR, path: '/color-converter', icon: Palette },
  { id: 'rgb-hex', name: 'RGB to HEX', description: 'Convert RGB to HEX.', category: ToolCategory.COLOR, path: '/color-converter', icon: Palette },
  { id: 'color-picker', name: 'Color Picker', description: 'Pick colors and get codes.', category: ToolCategory.COLOR, path: '/color-converter', icon: Eye },
  { id: 'css-grad-gen', name: 'CSS Gradient Gen', description: 'Generate Gradients.', category: ToolCategory.CSS_GEN, path: '/gradient-generator', icon: Palette },
  { id: 'js-min', name: 'JS Minify', description: 'Compress JavaScript.', category: ToolCategory.JS, path: '/code-minifier', icon: Minimize2 },
  { id: 'css-min', name: 'CSS Minify', description: 'Compress CSS code.', category: ToolCategory.CSS, path: '/code-minifier', icon: Minimize2 },
  { id: 'html-min', name: 'HTML Minify', description: 'Compress HTML.', category: ToolCategory.MINIFIER, path: '/code-minifier', icon: Minimize2 },
  // Note: Legacy hash algorithms provided for compatibility/debugging only
  { id: 'sha256', name: 'SHA Generator', description: 'Generate SHA256 Hash.', category: ToolCategory.CRYPTO, path: '/hash-generator', icon: ShieldCheck },
  { id: 'md5', name: 'MD5 Generator', description: 'Generate MD5 Hash.', category: ToolCategory.CRYPTO, path: '/hash-generator', icon: ShieldCheck },
  { id: 'jpg-png', name: 'JPG to PNG', description: 'Convert JPG to PNG.', category: ToolCategory.IMAGE_CONVERTER, path: '/image-converter', icon: Image },
  { id: 'png-jpg', name: 'PNG to JPG', description: 'Convert PNG to JPG.', category: ToolCategory.IMAGE_CONVERTER, path: '/image-converter', icon: Image },
  { id: 'img-base64', name: 'Image to Base64', description: 'Convert Image to Base64.', category: ToolCategory.BASE64, path: '/image-converter', icon: Image },
  { id: 'base64-img', name: 'Base64 to Image', description: 'Convert Base64 to Image.', category: ToolCategory.BASE64, path: '/image-converter', icon: Image },
  { id: 'bmp-png', name: 'BMP to PNG', description: 'Convert BMP to PNG.', category: ToolCategory.IMAGE_CONVERTER, path: '/image-converter', icon: Image },
  { id: 'length-converter', name: 'Length Converter', description: 'Convert length units.', category: ToolCategory.UNIT, path: '/unit-converter', icon: Ruler },
  { id: 'weight-converter', name: 'Weight Converter', description: 'Convert weight units.', category: ToolCategory.UNIT, path: '/unit-converter', icon: Calculator },
  { id: 'dec-bin', name: 'Decimal to Binary', description: 'Convert Dec to Bin.', category: ToolCategory.NUMBER, path: '/number-converter', icon: Calculator },
  { id: 'loan-calc', name: 'Loan Calculator', description: 'Calculate mortgage/loans.', category: ToolCategory.FINANCE, path: '/loan-calculator', icon: DollarSign },
  { id: 'html-table-gen', name: 'HTML Table Gen', description: 'Generate HTML Table.', category: ToolCategory.HTML_GEN, path: '/html-table-generator', icon: Table },
  { id: 'html-esc', name: 'HTML Escape', description: 'Escape HTML.', category: ToolCategory.ESCAPE, path: '/escape-tools', icon: Code },
  { id: 'html-md', name: 'HTML to Markdown', description: 'Convert HTML to Markdown.', category: ToolCategory.HTML, path: '/markdown-tools', icon: FileText },

  // --- MAPPED TOOLS ---
  { id: 'json-min', name: 'JSON Minify', description: 'Compress JSON.', category: ToolCategory.MINIFIER, path: '/json-formatter', icon: Minimize2 },
  { id: 'xml-val', name: 'XML Validator', description: 'Validate XML.', category: ToolCategory.VALIDATOR, path: '/xml-formatter', icon: ShieldCheck },
  { id: 'json-val', name: 'JSON Validator', description: 'Validate JSON.', category: ToolCategory.VALIDATOR, path: '/json-formatter', icon: ShieldCheck },
  { id: 'js-beautify', name: 'JS Beautifier', description: 'Format JavaScript.', category: ToolCategory.FORMATTER, path: '/code-formatter', icon: Code2 },
  { id: 'html-beautify', name: 'HTML Beautifier', description: 'Format HTML.', category: ToolCategory.FORMATTER, path: '/code-formatter', icon: Code },
  { id: 'css-beautify', name: 'CSS Beautifier', description: 'Format CSS code.', category: ToolCategory.CSS, path: '/code-formatter', icon: Braces },
  { id: 'json-xml', name: 'JSON to XML', description: 'Convert JSON to XML.', category: ToolCategory.JSON, path: '/json-converter', icon: ArrowRightLeft },
  { id: 'json-csv', name: 'JSON to CSV', description: 'Convert JSON to CSV.', category: ToolCategory.JSON, path: '/json-converter', icon: ArrowRightLeft },
  { id: 'tsv-csv', name: 'TSV to CSV', description: 'TSV to CSV.', category: ToolCategory.TSV, path: '/tsv-converter', icon: Table },
  { id: 'sql-csv', name: 'SQL to CSV', description: 'SQL to CSV conversion.', category: ToolCategory.SQL, path: '/sql-converter', icon: Table },
  { id: 'utf8-enc', name: 'UTF8 Encode', description: 'Encode to UTF8.', category: ToolCategory.UTF, path: '/utf8-converter', icon: Type },
  { id: 'utf8-dec', name: 'UTF8 Decode', description: 'Decode from UTF8.', category: ToolCategory.UTF, path: '/utf8-converter', icon: Type },
  { id: 'whois', name: 'Whois Lookup', description: 'Domain registration info.', category: ToolCategory.NETWORK, path: '/whois-lookup', icon: Search },
  { id: 'json-yaml', name: 'JSON to YAML', description: 'Convert JSON to YAML.', category: ToolCategory.JSON, path: '/yaml-converter', icon: ArrowRightLeft },
  { id: 'xml-yaml', name: 'XML to YAML', description: 'Convert XML to YAML.', category: ToolCategory.XML, path: '/yaml-converter', icon: ArrowRightLeft },
  { id: 'yaml-json', name: 'YAML to JSON', description: 'Convert YAML to JSON.', category: ToolCategory.YAML, path: '/yaml-converter', icon: ArrowRightLeft },
  { id: 'yaml-xml', name: 'YAML to XML', description: 'Convert YAML to XML.', category: ToolCategory.YAML, path: '/yaml-converter', icon: ArrowRightLeft },
  { id: 'js-val', name: 'JS Validator', description: 'Validate JavaScript.', category: ToolCategory.JS, path: '/js-validator', icon: ShieldCheck },

  // --- BATCH 9 (New Requests) ---
  { id: 'num-sort', name: 'Number Sorter', description: 'Sort lists of numbers.', category: ToolCategory.MATH, path: '/number-sorter', icon: Shuffle, isNew: true },
  { id: 'rm-punct', name: 'Remove Punctuation', description: 'Clean text symbols.', category: ToolCategory.STRING, path: '/remove-punctuation', icon: Type, isNew: true },
  { id: 'html-edit', name: 'HTML Editor', description: 'Real-time HTML/CSS editor.', category: ToolCategory.EDITOR, path: '/html-editor', icon: Code, isNew: true },
  { id: 'lua-min', name: 'Lua Minifier', description: 'Compress Lua code.', category: ToolCategory.MINIFIER, path: '/lua-minifier', icon: Minimize2, isNew: true },
  { id: 'lua-beauty', name: 'Lua Beautifier', description: 'Format Lua code.', category: ToolCategory.FORMATTER, path: '/lua-beautifier', icon: Wand2, isNew: true },
  { id: 'php-fmt', name: 'PHP Formatter', description: 'Beautify PHP code.', category: ToolCategory.FORMATTER, path: '/php-formatter', icon: Code2, isNew: true },
  { id: 'wp-hash', name: 'WP Password Hash', description: 'Generate WordPress hashes.', category: ToolCategory.CRYPTO, path: '/wordpress-password-hash', icon: Lock, isNew: true },
  { id: 'img-ascii', name: 'Image to ASCII', description: 'Convert image to text art.', category: ToolCategory.IMAGE_CONVERTER, path: '/image-to-ascii', icon: Image, isNew: true },
  { id: 'excel-view', name: 'Excel Viewer', description: 'View CSV/Excel data.', category: ToolCategory.CSV, path: '/excel-viewer', icon: FileSpreadsheet, isNew: true },
  { id: 'csv-excel', name: 'CSV to Excel', description: 'Convert CSV to Excel.', category: ToolCategory.CSV, path: '/csv-to-excel', icon: FileSpreadsheet, isNew: true },
  { id: 'paraphrase', name: 'Paraphrasing Tool', description: 'Rewrite text with AI.', category: ToolCategory.AI, path: '/paraphrasing-tool', icon: BrainCircuit, isNew: true },
  { id: 'mirror', name: 'Is It Down?', description: 'Check website status.', category: ToolCategory.NETWORK, path: '/mirror-online', icon: Wifi, isNew: true },
  { id: 'word-html', name: 'Word to HTML', description: 'Convert Word doc to HTML.', category: ToolCategory.HTML, path: '/word-to-html', icon: FileText, isNew: true },
  { id: 'share-link', name: 'Share Link Gen', description: 'Create social share links.', category: ToolCategory.TWITTER, path: '/sharelink-generator', icon: LinkIcon, isNew: true },

  { id: 'other', name: 'Other Tools', description: 'Miscellaneous tools.', category: ToolCategory.OTHER, path: '/other', icon: Box },
];
