import {
  Archive,
  ArrowRightLeft,
  Binary,
  Braces,
  BrainCircuit,
  Calculator,
  Clock,
  Code,
  Code2,
  Cpu,
  Database,
  DollarSign,
  Eye,
  FileCode,
  FileJson,
  FileSearch,
  FileText,
  Globe,
  Hash,
  Image,
  Key,
  Link as LinkIcon,
  Lock,
  Minimize2,
  Monitor,
  Palette,
  QrCode,
  Regex,
  Ruler,
  Search,
  Shield,
  ShieldCheck,
  Shuffle,
  Share2,
  Table,
  Type,
  Wand2,
  Wifi,
  GitCompare,
  Fingerprint,
  CalendarClock,
  Split,
  FileCode2,
  Terminal,
  FileSpreadsheet,
} from 'lucide-react';

import { ToolDef, ToolCategory } from '@/types';

export const ALL_TOOLS: ToolDef[] = [
  // --- ESSENTIAL DEVELOPER TOOLS ---
  {
    id: 'json-formatter',
    name: 'JSON Formatter',
    description: 'Beautify, minify and validate JSON.',
    category: ToolCategory.JSON,
    path: '/json-formatter',
    icon: FileJson,
    popular: true,
    tags: ['json', 'format', 'beautify', 'minify', 'validate', 'pretty print'],
  },
  {
    id: 'base64-converter',
    name: 'Base64 Converter',
    description: 'Encode and decode Base64 strings.',
    category: ToolCategory.CONVERTER,
    path: '/base64-converter',
    icon: Binary,
    popular: true,
    tags: ['base64', 'encode', 'decode', 'converter', 'encoding'],
  },
  {
    id: 'jwt-decoder',
    name: 'JWT Debugger',
    description: 'Decode JSON Web Tokens.',
    category: ToolCategory.DEV,
    path: '/jwt-decoder',
    icon: ShieldCheck,
    popular: true,
    tags: ['jwt', 'token', 'decode', 'auth', 'authentication', 'security'],
  },
  {
    id: 'regex-tester',
    name: 'Regex Tester',
    description: 'Test regular expressions.',
    category: ToolCategory.DEV,
    path: '/regex-tester',
    icon: Regex,
    popular: true,
    tags: ['regex', 'regexp', 'regular expression', 'pattern', 'match', 'test'],
  },
  {
    id: 'diff-viewer',
    name: 'Diff Viewer',
    description: 'Compare two text files.',
    category: ToolCategory.STRING,
    path: '/diff-viewer',
    icon: GitCompare,
    popular: true,
    tags: ['diff', 'compare', 'difference', 'merge', 'text comparison'],
  },
  // Note: MD5/SHA are provided as utility tools, not for security purposes
  {
    id: 'hash-generator',
    name: 'Hash & HMAC Generator',
    description:
      'Free online hash generator for MD5, SHA-256, SHA-512 and HMAC signatures. Generate secure checksums and message authentication codes instantly.',
    category: ToolCategory.CRYPTO,
    path: '/hash-generator',
    icon: Hash,
    popular: true,
    tags: [
      'hash',
      'md5',
      'sha',
      'sha256',
      'sha512',
      'sha384',
      'hmac',
      'checksum',
      'crypto',
      'signature',
      'message authentication',
      'file hash',
    ],
  },
  {
    id: 'uuid-generator',
    name: 'UUID Generator',
    description: 'Generate Version 4 UUIDs.',
    category: ToolCategory.RANDOM,
    path: '/uuid-generator',
    icon: Fingerprint,
    popular: true,
    tags: ['uuid', 'guid', 'unique id', 'random', 'identifier'],
  },
  {
    id: 'code-formatter',
    name: 'Code Beautifier',
    description: 'Format HTML, CSS, and JS.',
    category: ToolCategory.FORMATTER,
    path: '/code-formatter',
    icon: Wand2,
    popular: true,
    tags: ['code', 'format', 'beautify', 'html', 'css', 'js', 'javascript', 'prettier'],
  },
  {
    id: 'url-encoder',
    name: 'URL Encoder / Decoder',
    description: 'Encode/Decode URLs.',
    category: ToolCategory.ENCODE,
    path: '/url-encoder',
    icon: LinkIcon,
    popular: true,
    tags: ['url', 'encode', 'decode', 'uri', 'link', 'percent encoding'],
  },
  {
    id: 'date-converter',
    name: 'Date & Epoch Converter',
    description: 'Epoch & ISO date conversion.',
    category: ToolCategory.DEV,
    path: '/date-converter',
    icon: CalendarClock,
    popular: true,
    tags: ['date', 'epoch', 'unix', 'timestamp', 'iso', 'time'],
  },
  {
    id: 'sql-format',
    name: 'SQL Formatter',
    description: 'Format and beautify SQL queries.',
    category: ToolCategory.SQL,
    path: '/sql-formatter',
    icon: Database,
    popular: true,
    tags: ['sql', 'format', 'query', 'database', 'beautify'],
  },
  {
    id: 'password-generator',
    name: 'Password Generator',
    description: 'Generate secure passwords.',
    category: ToolCategory.RANDOM,
    path: '/password-generator',
    icon: Lock,
    popular: true,
    tags: ['password', 'generate', 'random', 'secure', 'strong password'],
  },

  // --- BATCH 8 (Ultimate Collection) ---
  {
    id: 'rsa-generator',
    name: 'RSA Key Generator',
    description: 'Generate PEM Public/Private keys.',
    category: ToolCategory.CRYPTO,
    path: '/rsa-generator',
    icon: Key,
  },
  {
    id: 'token-generator',
    name: 'Token Generator',
    description: 'Generate random API keys/secrets.',
    category: ToolCategory.RANDOM,
    path: '/token-generator',
    icon: Key,
  },
  {
    id: 'http-status-codes',
    name: 'HTTP Status Codes',
    description: 'Searchable status code reference.',
    category: ToolCategory.DEV,
    path: '/http-status-codes',
    icon: Globe,
  },
  {
    id: 'meta-tag-generator',
    name: 'Meta Tag Generator',
    description: 'SEO meta tags for websites.',
    category: ToolCategory.HTML_GEN,
    path: '/meta-tag-generator',
    icon: FileSearch,
  },
  {
    id: 'palette-extractor',
    name: 'Image Palette Extractor',
    description: 'Get colors from any image.',
    category: ToolCategory.COLOR,
    path: '/palette-extractor',
    icon: Palette,
  },

  // --- BATCH 7 (Final Polish) ---
  {
    id: 'markdown-editor',
    name: 'Markdown Converter',
    description: 'Write MD with live preview.',
    category: ToolCategory.EDITOR,
    path: '/markdown-editor',
    icon: FileText,
  },
  {
    id: 'bcrypt-generator',
    name: 'Bcrypt Generator',
    description: 'Hash and verify passwords.',
    category: ToolCategory.CRYPTO,
    path: '/bcrypt-generator',
    icon: Lock,
  },
  {
    id: 'bitwise-calculator',
    name: 'Bitwise Calculator',
    description: 'AND, OR, XOR, logic ops.',
    category: ToolCategory.MATH,
    path: '/bitwise-calculator',
    icon: Cpu,
  },
  {
    id: 'slug-generator',
    name: 'Slug Generator',
    description: 'URL-friendly text slug.',
    category: ToolCategory.STRING,
    path: '/slug-generator',
    icon: LinkIcon,
  },

  // --- BATCH 6 ---
  {
    id: 'list-comparator',
    name: 'List Comparator',
    description: 'Diff lists (Union, Intersection).',
    category: ToolCategory.STRING,
    path: '/list-comparator',
    icon: Split,
  },
  {
    id: 'case-converter',
    name: 'Text Case Converter',
    description: 'Camel, Snake, Kebab case.',
    category: ToolCategory.STRING,
    path: '/case-converter',
    icon: Type,
  },
  {
    id: 'ua-parser',
    name: 'User Agent Parser',
    description: 'Decode browser User Agent.',
    category: ToolCategory.DEV,
    path: '/ua-parser',
    icon: Monitor,
  },

  // --- BATCH 4 & 5 ---
  {
    id: 'gzip-compressor',
    name: 'GZip Compressor',
    description: 'Compress text to GZip Base64.',
    category: ToolCategory.COMPRESSION,
    path: '/gzip-compressor',
    icon: Archive,
  },
  {
    id: 'qrcode-generator',
    name: 'QR Code Generator',
    description: 'Generate QR Codes.',
    category: ToolCategory.HTML_GEN,
    path: '/qrcode-generator',
    icon: QrCode,
  },
  {
    id: 'chmod-calculator',
    name: 'Chmod Calculator',
    description: 'Linux permissions calculator.',
    category: ToolCategory.DEV,
    path: '/chmod-calculator',
    icon: Terminal,
  },
  {
    id: 'cron-generator',
    name: 'Cron Generator',
    description: 'Create cron schedule strings.',
    category: ToolCategory.DEV,
    path: '/cron-generator',
    icon: Clock,
    popular: true,
  },

  // --- PREVIOUSLY ADDED ---
  {
    id: 'xml-json-converter',
    name: 'XML <> JSON',
    description: 'Convert XML to JSON and back.',
    category: ToolCategory.XML,
    path: '/xml-json-converter',
    icon: ArrowRightLeft,
  },
  {
    id: 'dns-lookup',
    name: 'DNS Lookup',
    description: 'Find DNS records (A, MX, NS).',
    category: ToolCategory.NETWORK,
    path: '/dns-lookup',
    icon: Globe,
  },
  {
    id: 'pojo-generator',
    name: 'POJO Generator',
    description: 'Generate Java classes from JSON.',
    category: ToolCategory.POJO,
    path: '/pojo-generator',
    icon: FileCode2,
  },
  {
    id: 'utf8-converter',
    name: 'UTF-8 Converter',
    description: 'Text to Hex/Binary bytes.',
    category: ToolCategory.UTF,
    path: '/utf8-converter',
    icon: Binary,
  },
  {
    id: 'svg-viewer',
    name: 'SVG Viewer & Editor',
    description: 'View, edit and optimize SVGs.',
    category: ToolCategory.IMAGE_CONVERTER,
    path: '/svg-viewer',
    icon: Image,
    popular: true,
    tags: ['svg', 'vector', 'editor', 'viewer', 'optimize', 'convert'],
  },
  {
    id: 'csv-to-xml',
    name: 'CSV to XML Converter',
    description: 'Convert CSV files to XML format.',
    category: ToolCategory.CSV,
    path: '/csv-to-xml',
    icon: Table,
  },
  {
    id: 'csv-converter',
    name: 'CSV to JSON',
    description: 'Convert CSV to JSON format.',
    category: ToolCategory.CSV,
    path: '/csv-converter',
    icon: Table,
  },
  {
    id: 'css-unit-converter',
    name: 'CSS Unit Converter',
    description: 'Convert PX, REM, EM, %.',
    category: ToolCategory.CSS_UNIT,
    path: '/css-unit-converter',
    icon: Ruler,
  },
  {
    id: 'twitter-card-generator',
    name: 'Twitter Card Generator',
    description: 'Generate social meta tags.',
    category: ToolCategory.TWITTER,
    path: '/twitter-card-generator',
    icon: Share2,
  },
  {
    id: 'json-converter',
    name: 'JSON Converter',
    description: 'Convert JSON to XML/CSV.',
    category: ToolCategory.JSON,
    path: '/json-converter',
    icon: ArrowRightLeft,
  },
  {
    id: 'gst-calculator',
    name: 'GST Calculator',
    description: 'Calculate GST inclusive/exclusive.',
    category: ToolCategory.FINANCE,
    path: '/gst-calculator',
    icon: DollarSign,
  },
  {
    id: 'html-stripper',
    name: 'HTML Stripper',
    description: 'Remove HTML tags from text.',
    category: ToolCategory.HTML,
    path: '/html-stripper',
    icon: Code,
  },
  {
    id: 'random-generator',
    name: 'Random Generator',
    description: 'Generate random numbers/strings.',
    category: ToolCategory.RANDOM_GEN,
    path: '/random-generator',
    icon: Shuffle,
  },
  {
    id: 'tsv-converter',
    name: 'TSV to JSON',
    description: 'Convert TSV to JSON.',
    category: ToolCategory.TSV,
    path: '/tsv-converter',
    icon: Table,
  },
  {
    id: 'sql-converter',
    name: 'SQL to JSON',
    description: 'Convert SQL to JSON/CSV.',
    category: ToolCategory.SQL,
    path: '/sql-converter',
    icon: Database,
  },

  // --- OTHERS ---
  {
    id: 'ai-assistant',
    name: 'AI Code Helper',
    description: 'AI-powered code generation.',
    category: ToolCategory.AI,
    path: '/ai-assistant',
    icon: BrainCircuit,
    popular: true,
  },
  {
    id: 'my-ip',
    name: 'My IP Address',
    description: 'Show public IP & device info.',
    category: ToolCategory.NETWORK,
    path: '/my-ip',
    icon: Wifi,
  },
  {
    id: 'xml-formatter',
    name: 'XML Formatter',
    description: 'Format and validate XML data.',
    category: ToolCategory.XML,
    path: '/xml-formatter',
    icon: FileCode,
  },
  {
    id: 'word-counter',
    name: 'Word Counter',
    description: 'Count words and lines.',
    category: ToolCategory.STRING,
    path: '/word-counter',
    icon: Type,
  },
  {
    id: 'lorem-ipsum',
    name: 'Lorem Ipsum Generator',
    description: 'Generate filler text.',
    category: ToolCategory.STRING,
    path: '/lorem-ipsum',
    icon: FileText,
  },
  {
    id: 'text-styler',
    name: 'Text Styler',
    description: 'Fancy text generator.',
    category: ToolCategory.TEXT_STYLE,
    path: '/text-styler',
    icon: Type,
  },
  {
    id: 'hex-rgb',
    name: 'Color Converter',
    description: 'Convert between color formats.',
    category: ToolCategory.COLOR,
    path: '/color-converter',
    icon: Palette,
  },
  {
    id: 'rgb-hex',
    name: 'Color Converter',
    description: 'Convert between color formats.',
    category: ToolCategory.COLOR,
    path: '/color-converter',
    icon: Palette,
  },
  {
    id: 'color-picker',
    name: 'Color Picker',
    description: 'Pick colors and get codes.',
    category: ToolCategory.COLOR,
    path: '/color-converter',
    icon: Eye,
  },
  {
    id: 'gradient-generator',
    name: 'CSS Gradient Generator',
    description: 'Generate Gradients.',
    category: ToolCategory.CSS_GEN,
    path: '/gradient-generator',
    icon: Palette,
  },
  {
    id: 'js-min',
    name: 'JS Minify',
    description: 'Compress JavaScript.',
    category: ToolCategory.JS,
    path: '/code-minifier',
    icon: Minimize2,
  },
  {
    id: 'css-min',
    name: 'CSS Minify',
    description: 'Compress CSS code.',
    category: ToolCategory.CSS,
    path: '/code-minifier',
    icon: Minimize2,
  },
  {
    id: 'html-min',
    name: 'HTML Minify',
    description: 'Compress HTML.',
    category: ToolCategory.MINIFIER,
    path: '/code-minifier',
    icon: Minimize2,
  },
  // Note: Legacy hash algorithms provided for compatibility/debugging only
  {
    id: 'sha256',
    name: 'SHA Generator',
    description: 'Generate SHA256 Hash.',
    category: ToolCategory.CRYPTO,
    path: '/hash-generator',
    icon: ShieldCheck,
  },
  {
    id: 'md5',
    name: 'MD5 Generator',
    description: 'Generate MD5 Hash.',
    category: ToolCategory.CRYPTO,
    path: '/hash-generator',
    icon: ShieldCheck,
  },
  {
    id: 'jpg-png',
    name: 'JPG to PNG',
    description: 'Convert JPG to PNG.',
    category: ToolCategory.IMAGE_CONVERTER,
    path: '/image-converter',
    icon: Image,
  },
  {
    id: 'png-jpg',
    name: 'PNG to JPG',
    description: 'Convert PNG to JPG.',
    category: ToolCategory.IMAGE_CONVERTER,
    path: '/image-converter',
    icon: Image,
  },
  {
    id: 'img-base64',
    name: 'Image to Base64',
    description: 'Convert Image to Base64.',
    category: ToolCategory.BASE64,
    path: '/image-converter',
    icon: Image,
    popular: true,
  },
  {
    id: 'base64-img',
    name: 'Base64 to Image',
    description: 'Convert Base64 to Image.',
    category: ToolCategory.BASE64,
    path: '/image-converter',
    icon: Image,
  },
  {
    id: 'bmp-png',
    name: 'BMP to PNG',
    description: 'Convert BMP to PNG.',
    category: ToolCategory.IMAGE_CONVERTER,
    path: '/image-converter',
    icon: Image,
  },
  {
    id: 'length-converter',
    name: 'Length Converter',
    description: 'Convert length units.',
    category: ToolCategory.UNIT,
    path: '/unit-converter',
    icon: Ruler,
  },
  {
    id: 'weight-converter',
    name: 'Weight Converter',
    description: 'Convert weight units.',
    category: ToolCategory.UNIT,
    path: '/unit-converter',
    icon: Calculator,
  },
  {
    id: 'dec-bin',
    name: 'Decimal to Binary',
    description: 'Convert Dec to Bin.',
    category: ToolCategory.NUMBER,
    path: '/number-converter',
    icon: Calculator,
  },
  {
    id: 'loan-calculator',
    name: 'Loan Calculator',
    description: 'Calculate mortgage/loans.',
    category: ToolCategory.FINANCE,
    path: '/loan-calculator',
    icon: DollarSign,
  },
  {
    id: 'html-table-generator',
    name: 'HTML Table Generator',
    description: 'Generate HTML Table.',
    category: ToolCategory.HTML_GEN,
    path: '/html-table-generator',
    icon: Table,
  },
  {
    id: 'html-esc',
    name: 'String Escaper & Encoder',
    description: 'Escape HTML.',
    category: ToolCategory.ESCAPE,
    path: '/escape-tools',
    icon: Code,
  },
  {
    id: 'html-md',
    name: 'HTML to Markdown',
    description: 'Convert HTML to Markdown.',
    category: ToolCategory.HTML,
    path: '/markdown-tools',
    icon: FileText,
  },

  // --- MAPPED TOOLS ---
  {
    id: 'json-min',
    name: 'JSON Minify',
    description: 'Compress JSON.',
    category: ToolCategory.MINIFIER,
    path: '/json-formatter',
    icon: Minimize2,
  },
  {
    id: 'xml-val',
    name: 'XML Validator',
    description: 'Validate XML.',
    category: ToolCategory.VALIDATOR,
    path: '/xml-formatter',
    icon: ShieldCheck,
  },
  {
    id: 'json-val',
    name: 'JSON Validator',
    description: 'Validate JSON.',
    category: ToolCategory.VALIDATOR,
    path: '/json-formatter',
    icon: ShieldCheck,
  },
  {
    id: 'js-beautify',
    name: 'JS Beautifier',
    description: 'Format JavaScript.',
    category: ToolCategory.FORMATTER,
    path: '/code-formatter',
    icon: Code2,
  },
  {
    id: 'html-beautify',
    name: 'HTML Beautifier',
    description: 'Format HTML.',
    category: ToolCategory.FORMATTER,
    path: '/code-formatter',
    icon: Code,
  },
  {
    id: 'css-beautify',
    name: 'CSS Beautifier',
    description: 'Format CSS code.',
    category: ToolCategory.CSS,
    path: '/code-formatter',
    icon: Braces,
  },
  {
    id: 'json-xml',
    name: 'JSON to XML',
    description: 'Convert JSON to XML.',
    category: ToolCategory.JSON,
    path: '/json-converter',
    icon: ArrowRightLeft,
  },
  {
    id: 'json-csv',
    name: 'JSON to CSV',
    description: 'Convert JSON to CSV.',
    category: ToolCategory.JSON,
    path: '/json-converter',
    icon: ArrowRightLeft,
  },
  {
    id: 'tsv-csv',
    name: 'TSV to CSV',
    description: 'TSV to CSV.',
    category: ToolCategory.TSV,
    path: '/tsv-converter',
    icon: Table,
  },
  {
    id: 'sql-csv',
    name: 'SQL to CSV',
    description: 'SQL to CSV conversion.',
    category: ToolCategory.SQL,
    path: '/sql-converter',
    icon: Table,
  },
  {
    id: 'utf8-enc',
    name: 'UTF-8 Encode',
    description: 'Encode to UTF8.',
    category: ToolCategory.UTF,
    path: '/utf8-converter',
    icon: Type,
  },
  {
    id: 'utf8-dec',
    name: 'UTF-8 Decode',
    description: 'Decode from UTF8.',
    category: ToolCategory.UTF,
    path: '/utf8-converter',
    icon: Type,
  },
  {
    id: 'whois-lookup',
    name: 'Whois Lookup',
    description: 'Domain registration info.',
    category: ToolCategory.NETWORK,
    path: '/whois-lookup',
    icon: Search,
  },
  {
    id: 'json-yaml',
    name: 'JSON to YAML',
    description: 'Convert JSON to YAML.',
    category: ToolCategory.JSON,
    path: '/yaml-converter',
    icon: ArrowRightLeft,
  },
  {
    id: 'xml-yaml',
    name: 'XML to YAML',
    description: 'Convert XML to YAML.',
    category: ToolCategory.XML,
    path: '/yaml-converter',
    icon: ArrowRightLeft,
  },
  {
    id: 'yaml-json',
    name: 'YAML to JSON',
    description: 'Convert YAML to JSON.',
    category: ToolCategory.YAML,
    path: '/yaml-converter',
    icon: ArrowRightLeft,
  },
  {
    id: 'yaml-xml',
    name: 'YAML to XML',
    description: 'Convert YAML to XML.',
    category: ToolCategory.YAML,
    path: '/yaml-converter',
    icon: ArrowRightLeft,
  },
  {
    id: 'js-validator',
    name: 'JS Validator',
    description: 'Validate JavaScript.',
    category: ToolCategory.JS,
    path: '/js-validator',
    icon: ShieldCheck,
  },

  // --- BATCH 9 ---
  {
    id: 'number-sorter',
    name: 'Number Sorter',
    description: 'Sort lists of numbers.',
    category: ToolCategory.MATH,
    path: '/number-sorter',
    icon: Shuffle,
  },
  {
    id: 'remove-punctuation',
    name: 'Remove Punctuation',
    description: 'Clean text symbols.',
    category: ToolCategory.STRING,
    path: '/remove-punctuation',
    icon: Type,
  },
  {
    id: 'html-editor',
    name: 'Real-time HTML Editor',
    description: 'Real-time HTML/CSS editor.',
    category: ToolCategory.EDITOR,
    path: '/html-editor',
    icon: Code,
  },
  {
    id: 'lua-formatter',
    name: 'Lua Formatter',
    description:
      'Free online Lua code formatter. Beautify or minify Lua scripts with proper indentation, formatting and compression.',
    category: ToolCategory.FORMATTER,
    path: '/lua-formatter',
    icon: Code2,
    tags: [
      'lua',
      'format',
      'beautify',
      'minify',
      'lua beautifier',
      'lua minifier',
      'code formatter',
      'lua script',
      'game scripting',
    ],
  },
  {
    id: 'php-formatter',
    name: 'PHP Formatter',
    description: 'Beautify PHP code.',
    category: ToolCategory.FORMATTER,
    path: '/php-formatter',
    icon: Code2,
  },
  {
    id: 'wordpress-password-hash',
    name: 'WordPress Password Hash',
    description: 'Generate WordPress hashes.',
    category: ToolCategory.CRYPTO,
    path: '/wordpress-password-hash',
    icon: Lock,
  },
  {
    id: 'image-to-ascii',
    name: 'Image to ASCII',
    description: 'Convert image to text art.',
    category: ToolCategory.IMAGE_CONVERTER,
    path: '/image-to-ascii',
    icon: Image,
  },
  {
    id: 'excel-viewer',
    name: 'Excel / CSV Viewer',
    description: 'View CSV/Excel data.',
    category: ToolCategory.CSV,
    path: '/excel-viewer',
    icon: FileSpreadsheet,
  },
  {
    id: 'csv-to-excel',
    name: 'CSV to Excel',
    description: 'Convert CSV to Excel.',
    category: ToolCategory.CSV,
    path: '/csv-to-excel',
    icon: FileSpreadsheet,
  },

  // --- NEW TOOLS ---
  {
    id: 'paraphrasing-tool',
    name: 'Paraphrasing Tool',
    description: 'Rewrite text with AI.',
    category: ToolCategory.AI,
    path: '/paraphrasing-tool',
    icon: BrainCircuit,
    isNew: true,
  },
  {
    id: 'mirror-online',
    name: 'Is It Down?',
    description: 'Check website status.',
    category: ToolCategory.NETWORK,
    path: '/mirror-online',
    icon: Wifi,
  },
  {
    id: 'word-to-html',
    name: 'Word to HTML',
    description: 'Convert Word doc to HTML.',
    category: ToolCategory.HTML,
    path: '/word-to-html',
    icon: FileText,
    isNew: true,
  },
  {
    id: 'sharelink-generator',
    name: 'Share Link Generator',
    description: 'Create social share links.',
    category: ToolCategory.TWITTER,
    path: '/sharelink-generator',
    icon: LinkIcon,
    isNew: true,
  },
  {
    id: 'readme-generator',
    name: 'Readme Generator',
    description: 'Create professional READMEs.',
    category: ToolCategory.EDITOR,
    path: '/readme-generator',
    icon: FileText,
    isNew: true,
    popular: true,
    tags: ['readme', 'generator', 'markdown', 'documentation'],
  },
];
